### ISSUE TITLE
Missing wheel package on PyPI

### ISSUE THREAD

**Issue by jdufresne** [azavea/django-amazon-ses#12]
I see that `setup.cfg` is set to build universal wheels:

https://github.com/azavea/django-amazon-ses/blob/develop/setup.cfg#L2

I also see Travis is configured to upload wheels when a tag is created:

https://github.com/azavea/django-amazon-ses/blob/develop/.travis.yml#L43

However, the PyPI page does not have a wheel, only a `.tar.gz` file.

https://pypi.python.org/pypi/django-amazon-ses

**Comment by hectcastro** [comment]
Fixed via https://github.com/azavea/django-amazon-ses/commit/46a52d44f38001eaf84f49eb56af33985dd26170.

**Comment by jdufresne** [comment]
Wheel is now on PyPI. Thanks!
