### ISSUE TITLE
 are all the django.core.mail methods supported by this application ?

### ISSUE THREAD

**Issue by younes-alouani** [azavea/django-amazon-ses#42]
I went through all the documentation.
There no chapter explaining the Django methods supported. Is that normal ?
Can I send mass mails ?
Is html_content supported ?
Can I include links and anchors in mail content ?
Is this example working ?

```
from django.core import mail
connection = mail.get_connection()

# Manually open the connection
connection.open()

# Construct an email message that uses the connection
email1 = mail.EmailMessage(
    'Hello',
    'Body goes here',
    'from@example.com',
    ['to1@example.com'],
    connection=connection,
)
email1.send() # Send the email

# Construct two more messages
email2 = mail.EmailMessage(
    'Hello',
    'Body goes here',
    'from@example.com',
    ['to2@example.com'],
)
email3 = mail.EmailMessage(
    'Hello',
    'Body goes here',
    'from@example.com',
    ['to3@example.com'],
)

# Send the two emails in a single call -
connection.send_messages([email2, email3])
# The connection was already open so send_messages() doesn't close it.
# We need to manually close the connection.
connection.close()
```

And can I do this ? 
```
if html_message:
            email.content_subtype = 'html'
email.send()
```

**Comment by hectcastro** [comment]
Hey @younes-alouani, we implement `send_messages(email_messages)`, which gets used by the other Django email backend methods.

See: https://docs.djangoproject.com/en/2.1/topics/email/#defining-a-custom-email-backend

We use this module in production to send text and HTML based emails. For an example of how we send HTML emails, see:

https://github.com/OpenTreeMap/otm-core/blob/7b57c6ef96cd66f4381105af009f22f52938bfd7/opentreemap/manage_treemap/lib/email.py#L17-L28

**Comment by younes-alouani** [comment]
Thank you Sir. Very happy to read the code of your project. 
I still have a question : 
Your templates are .txt. Does this mean the links can't be clicked ? So The user needs to copy paste them in the browser ? Or am I wrong ?

**Comment by hectcastro** [comment]
I think we used `txt` in the name of variables there just because the templates are plain text. If you create `<a>` tags in the message and use a `text/html` MIME type, it should render as a link for email clients that support HTML messages.
