### ISSUE TITLE
Django cant find "ModuleNotFoundError: No module named 'django_amazon_ses'" in no debug mode.

### ISSUE THREAD

**Issue by emilpriver** [azavea/django-amazon-ses#49]
Hi,

first of all, great module! Does alot of good work.

Im am currently having an problem where when i run the code on my server in production mode does django not find "django_amazon_ses" in "EMAIL_BACKEND" but i am able to work with the module in non production flawless.

![38bb62366f7ef27686d847aa00771dc9](https://user-images.githubusercontent.com/34039674/70365157-534af500-1890-11ea-8542-4fd85dc170f1.png)

Where implement the code:
![4dc14dab6c70655d37a825bb31c35d74](https://user-images.githubusercontent.com/34039674/70365167-68278880-1890-11ea-91af-fd4d1f1b99d2.png)

The thing is that when i run locally in production am I able to run the function but when I run it on the server does it not find the module.

Is there any solution on this problem?

Dear,
Emil

**Comment by hectcastro** [comment]
Hm. Is this a code snippet from `settings.py`? If so, see this example of how we initialize the email backend. Note how we make sure to initialize at least one no matter which branch of the `if` statement we take:

https://github.com/open-apparel-registry/open-apparel-registry/blob/242a5e7932823ec5c14141c12b354d8da98e3259/src/django/oar/settings.py#L273-L276

The console backend is particularly useful for development. Also, have you made sure to add `django-amazon-ses` to whatever process you use to install dependencies across all environments?

**Comment by emilpriver** [comment]
Hello, So basic i need to remove the email_backend and it might work? "django_amazon_ses.EmailBackend" should be used when im running in production on the server doe.  i will try and reach back!

Yes, Django-amazon-ses is in my requirements file and is installed on every docker build.

Thank you for your reply!

**Comment by emilpriver** [comment]
Hi again, i removed "EMAIL_BACKEND = 'django_amazon_ses.EmailBackend'" from settings.py. But do now get "[Errno 99] Address not available" Is this related to your module?

**Comment by hectcastro** [comment]
I don't think so. This sounds like a lower level exception being raised by the `socket` module in Python.

**Comment by emilpriver** [comment]
Cool, I will continue investigate, I dont think the problem is the module. More something else! Thank you! :D
