### ISSUE TITLE
Double send of signal 

### ISSUE THREAD

**Issue by mtb-beta** [azavea/django-amazon-ses#50]
There is double send of signal as below at develop branch.

https://github.com/azavea/django-amazon-ses/blob/develop/django_amazon_ses.py#L122-L125
```python
            message_id = result["MessageId"]
            post_send.send(self.__class__, message=email_message, message_id=message_id)
            message_id = result["MessageId"]
            post_send.send(self.__class__, message=email_message, message_id=message_id)
```

There is not double send in PR. https://github.com/azavea/django-amazon-ses/pull/45

But it included at https://github.com/azavea/django-amazon-ses/commit/694207c522f8443942bf7ce9fd2e5ce4e4f9bb98 .

I think it mistake of cherypick.

**Comment by hectcastro** [comment]
Hey @mtb-beta, thanks for pointing this out. The fix was included in the 3.0.1 release: https://github.com/azavea/django-amazon-ses/releases/tag/3.0.1.
