### ISSUE TITLE
does this allow using ses templated emails?

### ISSUE THREAD

**Issue by krystofbe** [azavea/django-amazon-ses#69]
Hi theres,

Amazon SES allows sending templated: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-personalized-email-api.html

is this supported by this package?

**Comment by hectcastro** [comment]
Hey @krystofbe, it does not.

Because we work through the Django email backend API, we depend on the template functionality provided by Django to solve issues related to templating.

**Comment by krystofbe** [comment]
Ok thanks
